# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '$(Build.SourcesDirectory)/src/azure-function/FileProcessor.csproj'
    feedsToUse: 'select'
    vstsFeed: '906a4f3f-08d4-4012-bf06-95483d24d1c0'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)/src/azure-function/FileProcessor.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(Build.SourcesDirectory)/src/azure-function/FileProcessor.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
    workingDirectory: '$(Build.SourcesDirectory)/src/azure-function'

- task: PublishBuildArtifacts@1
  displayName: 'Create Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
    ArtifactName: 'drop'
    publishLocation: 'Container'